const PUSH_NOTIF_TIME = 9; // range from 0 to 23
const PUSH_NOTIF_TIME_HHMMSS = "09:00:00";
const QUERY_USER_BIRTHDAY_AGENDA_INTERVAL = "0 0 * * *"; // every day at 00:00
const MILLISECOND_IN_A_DAY = 24 * 60 * 60 * 1000;
const ONE_HOUR_IN_MILLISECOND = 60 * 60 * 1000;
const LEAP_YEAR_DATE = "02-29";
const LEAP_YEAR_REPLACEMENT_DATE = "02-28";

export {
  PUSH_NOTIF_TIME,
  PUSH_NOTIF_TIME_HHMMSS,
  QUERY_USER_BIRTHDAY_AGENDA_INTERVAL,
  MILLISECOND_IN_A_DAY,
  ONE_HOUR_IN_MILLISECOND,
  LEAP_YEAR_DATE,
  LEAP_YEAR_REPLACEMENT_DATE,
};
