const PUSH_NOTIF_TIME = 10; // range from 0 to 23
const PUSH_NOTIF_TIME_HHMMSS = "10:26:00";
const QUERY_USER_BIRTHDAY_AGENDA_INTERVAL = "25 3 * * *"; // every day at 00:00
const MILLISECOND_IN_A_DAY = 24 * 60 * 60 * 1000;


export {
  PUSH_NOTIF_TIME,
  PUSH_NOTIF_TIME_HHMMSS,
  QUERY_USER_BIRTHDAY_AGENDA_INTERVAL,
  MILLISECOND_IN_A_DAY,
}