const PUSH_NOTIF_TIME = 9; // range from 0 to 23
const QUERY_USER_BIRTHDAY_AGENDA_INTERVAL = "0 0 * * *"; // every day at 00:00
const MILLISECOND_IN_A_DAY = 24 * 60 * 60 * 1000;


export {
  PUSH_NOTIF_TIME,
  QUERY_USER_BIRTHDAY_AGENDA_INTERVAL,
  MILLISECOND_IN_A_DAY,
}