version: "3.4"

services:
  dana-modal-app:
    image: dana-modal-be-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8081:8081"
